FROM registry.git.lab/cisco-devops/containers/postgres:latest

# metadata
LABEL description="This is a postgres db for net inventory Flask app"
LABEL maintainer="Cisco <noreply@cisco.com>"
LABEL version="0.1"

# doesn't actually do anything, just documentation purposes. forward your port at runtime
EXPOSE 5432/tcp

