---
INSIDE:
  interface: inside
  policies:
    - action: permit
      protocol: icmp
      source:
        ip: 10.10.0.0
        mask: 22
      destination:
        ip: 10.10.3.0
        mask: 24
OUTSIDE:
  interface: outside
  policies:
    - action: permit
      protocol: icmp
      source: 
        ip: 10.10.3.0
        mask: 24
      destination:
        ip: 10.10.0.0
        mask: 22

