---
- hosts: linuxhosts
  # Become root user
  become: true
  tasks:
    - name: uninstall nginx on ubuntu
      apt: name=nginx state=absent
      # Do the above above if facts comes back as Debian - Ubuntu
      when: ansible_os_family == "Debian"

    - name: uninstall nginx on centos
      yum: name=nginx state=absent
      # Do the above if facts comes back as RedHat - CentOS
      when: ansible_os_family == "RedHat"