---
- hosts: centoshosts
  tasks:
    - name: print OS family to file
      # Use data from facts dictionary as variable
      shell: echo "The family is {{ansible_os_family}}" > /{{ansible_user_id}}/files/family.txt
    - name: Print Default Machine NIC Name to console
      debug: msg="{{ansible_default_ipv4.interface}}"
    - name: Register ls results variable
      command: "ls"
      # Store output of the above ls task as variable dirs
      register: dirs
    - name: Print dirs variable from last step to console
      debug:
        msg: "{{dirs}}"