---
- name: "CREATE AND DEPLOY FIREWALL CONFIGURATIONS"
  hosts: "firewalls"
  gather_facts: no
  tasks:
    
    - name: "LOAD CONFIG VARIABLES FROM VARS FILE"
      include_vars:
        file: "vars/{{ inventory_hostname }}/{{ item }}.yml"
        name: "{{ item }}_config"
      loop: ["interfaces", "bgp", "policies"]
      delegate_to: "localhost"

    - name: "BUILD CONFIGURATION ARTIFACTS FOR DEVICES"
      template:
        src: "templates/firewalls.j2"
        dest: "outputs/configs/{{ inventory_hostname }}"
      delegate_to: "localhost"

    - name: "CHECK IF DEVICE IS REACHABLE" 
      wait_for: 
        host: "{{ ansible_host }}" 
        port: 22 
        timeout: 600 
      delegate_to: "localhost" 

    - name: "DEPLOY CONFIGURATION ARTIFACTS TO DEVICES"
      asa_config:
        src: "outputs/configs/{{ inventory_hostname }}"
        save: True
