---
GigabitEthernet0/0:
  zone:
    name: "inside"
    security_level: 100
  ip_address:
    ip: "10.10.4.254"
    mask: 24
GigabitEthernet0/1:
  zone:
    name: "outside"
    security_level: 0
  ip_address:
    ip: "10.10.3.1"
    mask: 24
