FROM suhaibasaeed/postgres:latest

# metadata
LABEL description="This is a postgresDB"
LABEL maintainer="Cisco <noreply@cisco.com>"
LABEL version="0.1"

ENV POSTGRES_DB=net_inventory
ENV POSTGRES_USER=root
ENV POSTGRES_PASSWORD=Cisco123
ENV PGDATA=/var/lib/postgresql/data/pgdata

EXPOSE 5432/tcp
