FROM suhaibasaeed/python37:latest

# metadata
LABEL description="This is a net inventory frontend flask application"
LABEL maintainer="Cisco <noreply@cisco.com>"
LABEL version="0.1"

# copy files over to container
ADD ./ /net_inventory

# sets the working directory
WORKDIR /net_inventory/

# install system packages
RUN apt install -y git vim

# install python packages
RUN pip install -r ./requirements.txt

# Add Environment Variables
ENV ENV=FRONTEND
ENV URL=http://netinv_backend:5001

# doesn't actually do anything, just documentation purposes. forward your port at runtime
EXPOSE 5000/tcp

# start the application
ENTRYPOINT python run.py

