---
- name: Gather IOS-XE Facts
  hosts: sandbox
  connection: local
  tasks:
    - name: Gather IOS Facts
      ios_facts:
        provider:
          host: ios-xe-mgmt.cisco.com
          port: 8181
          username: developer
          password: C1sco12345

    - name: What is the IOS OS ver?
      debug:
        var: ansible_net_version

    - name: What is the hostname?
      debug:
        var: ansible_net_hostname