---
- name: "VALIDATE SERVERS STATE"
  hosts: "k8s"
  gather_facts: "yes"
  tasks:

    - name: "DEBUG ANSIBLE FACTS"
      debug: 
        msg: "{{ ansible_facts['eth0']['ipv4']['address'] }}"

    - name: "CHECK TCP PORT 22"
      wait_for:
        host: "{{ ansible_host }}"
        port: 22
        delay: 3
        timeout: 100

    - name: "SET FACT: GET LINUX IP-S"
      set_fact:
        linux_ip_address: "{{ ansible_facts['eth0']['ipv4']['address'] }}"

    - name: "SET FACT: LINUX NEIGHBORS"
      set_fact:
        linux_neighbors: "{{ linux_neighbors | default([]) + [ hostvars[item]['linux_ip_address'] ] }}"
      when: "item != inventory_hostname"
      loop: "{{ ansible_play_batch }}"

    - debug: var=linux_neighbors

    - name: "PING TEST"
      command: "ping -c 1 {{ item }}"
      delegate_to: "{{ inventory_hostname }}"
      loop: "{{ linux_neighbors }}"
      changed_when: False
